1.Найдите собственные векторы и собственные значения для линейного
оператора заданного матрицей

In [1]:
import numpy as np

In [2]:
A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)

print(f'Matrix A:\n{A}')
print(f'Eigenvalues:\n{w}')
print(f'Eigenvectors:\n{v}')

Matrix A:
[[-1 -6]
 [ 2  6]]
Eigenvalues:
[2. 3.]
Eigenvectors:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


2.Дан оператор поворота на 180 градусов задаваемый матрицей
A=([[−1, 0], [0, −1]]). Покажите что , любой вектор считается для него собственным.

In [5]:
A = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(A)

print(f'Matrix A:\n {A}')
print(f'Eigenvectors:\n {v}')
print(f'Eigenvalues:\n {w}')

Matrix A:
 [[-1  0]
 [ 0 -1]]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]
Eigenvalues:
 [-1. -1.]


Система верна при любых значениях и это означает что любой вектор x y, ,
является для данного оператора собственным.

3.Пусть линейный оператор задан матрицей A=([[1, 1],[−1, 3]]). Установите считается ли вектор , x=(1 ,1) собственным вектором этого линейного оператора.

In [8]:
A = np.array([[1, 1], [-1, 3]])
x = np.array([1, 1])

print(f'Matrix x:\n {A.dot(x)}')

Matrix x:
 [2 2]


Система верна при заданных значениях, значит, вектор является собственным.

4.Пусть линейный оператор задан матрицей A=([[0, 3, 0], [3, 0, 0], [0, 0, 3]]).
Установите считается ли вектор , x=(3 ,−3,−4) собственным вектором этого
линейного оператора.

In [9]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
x = np.array([3, -3, -4])

print(f'Matrix x:\n {A.dot(x)}')

Matrix x:
 [ -9   9 -12]


т.к. решением системы является -3, то вектор x=(3,−3,−4) является собственным вектором.