#Системы линейных уравнений.

1. Проверьте на совместность и выясните сколько решений будет иметь
система линейных уравнений :

In [1]:
import numpy as np

In [2]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, -17, 0])[:, np.newaxis]
A_extended = np.hstack((A, b))
print(f'rank A = {np.linalg.matrix_rank(A)}')
print(f'rank A_extended = {np.linalg.matrix_rank(A_extended)}')

# Число неизвестных система совместна и имеет единственное решение

rank A = 3
rank A_extended = 3


In [3]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5])[:, np.newaxis]
A_extended = np.hstack((A, b))
print(f'rank A = {np.linalg.matrix_rank(A)}')
print(f'rank A_extended = {np.linalg.matrix_rank(A_extended)}')

# Система не совместна и не имеет решений

rank A = 1
rank A_extended = 2


In [4]:
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2])[:, np.newaxis]
A_extended = np.hstack((A, b))
print(f'rank A = {np.linalg.matrix_rank(A)}')
print(f'rank A_extended = {np.linalg.matrix_rank(A_extended)}')

# Pанги матриц равны 2, но число неизвестных - 3, система имеет бесконечное количество решений.

rank A = 2
rank A_extended = 2


2. Проверьте на совместность и выясните, сколько решений будет иметь
система линейных уравнений, заданная расширенной матрицей:

In [5]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([[3], [2], [4], [1]])
A_ext = np.hstack((A, b))
print(f'Система совместна: {np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_ext)}')
print(f'Имеет единственное решение: {np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_ext) == 4}')

Система совместна: True
Имеет единственное решение: True


3.Дана система линейных уравнений заданная расширенной матрицей.
Найдите соотношение между параметрами a, b и c, при которых система
считается несовместной.

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A[2] = A[2] - 2*A[1] + A[0]
print(f'Matrix A:\n {A}')

# Чтобы система была несовместной нужно чтобы после преобразований в расширенной матрице в третьей строке свободных членов был не то 0, есть c −2b+a≠ 0.

Matrix A:
 [[1 2 3]
 [4 5 6]
 [0 0 0]]


 4.Решите систему уравнений методом Крамера

In [12]:
def kramer(A, b):
  assert A.shape[0] == A.shape[1], 'Wrong matrix size!'
  det_A = np.linalg.det(A)
  result = []
  if np.abs(det_A) > 0.000001:
    for i in range(A.shape[0]):
      A_i = np.hstack((A[:, :i], b, A[:, i+1:]))
      result.append(np.linalg.det(A_i) / det_A)
    return np.round(result, 2)
  else:
    return 'det A is 0'

In [13]:
A = np.array([[1, -2], [3, -4]])
b = np.array([[1, 7]]).T
print(f'{kramer(A, b)}')

[5. 2.]


In [14]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([[10, -2, 1]]).T
print(f'{kramer(A, b)}')

[ 2. -1.  1.]
