# Part 1

In [1]:
# 1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц

import numpy as np

In [3]:
A = np.ones((4, 2))
B = np.ones((4, 2))
print(f'Matrix A\n{A}\n')
print(f'Matrix B\n{B}\n')
print(f'Matrix AB\n {np.dot(A, B)}')
print(f'Matrix BA\n {np.dot(B, A)}')

Matrix A
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Matrix B
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]



ValueError: ignored

Перемножение не возможно, т.к. количество столбцов первой матрицы не равно количеству строк второй при перемножении.

In [4]:
A = np.ones((2, 5))
B = np.ones((5, 3))
print(f'Matrix A\n{A}\n')
print(f'Matrix B\n{B}\n')
print(f'Matrix AB\n {np.dot(A, B)}')
print(f'Matrix BA\n {np.dot(B, A)}')

Matrix A
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Matrix B
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matrix AB
 [[5. 5. 5.]
 [5. 5. 5.]]


ValueError: ignored

Перемножить АВ можно - соответвует размерность, перемножить ВА нельзя - нарушена размерность матрицы.

In [5]:
A = np.ones((8, 3))
B = np.ones((3, 8))
print(f'Matrix A\n{A}\n')
print(f'Matrix B\n{B}\n')
print(f'Matrix AB\n {np.dot(A, B)}')
print(f'Matrix BA\n {np.dot(B, A)}')

Matrix A
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matrix B
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

Matrix AB
 [[3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]]
Matrix BA
 [[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]


Перемножение матриц прошло успешно, размерность не нарушена в обоих случаях перемножения.

In [6]:
A = np.ones((4, 4))
B = np.ones((4, 4))
print(f'Matrix A\n{A}\n')
print(f'Matrix B\n{B}\n')
print(f'Matrix AB\n {np.dot(A, B)}')
print(f'Matrix BA\n {np.dot(B, A)}')

Matrix A
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Matrix B
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Matrix AB
 [[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
Matrix BA
 [[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


Перемножение матриц прошло успешно, размерность не нарушена в обоих случаях перемножения.

2. Найдите сумму и произведение матриц

In [8]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Matrix A\n {A}')
print(f'Matrix B\n {B}')
print(f'Matrix SUM AB\n {A+B}')
print(f'Matrix AB\n {np.dot(A, B)}')
print(f'Matrix BA\n {np.dot(B, A)}')

Matrix A
 [[ 1 -2]
 [ 3  0]]
Matrix B
 [[ 4 -1]
 [ 0  5]]
Matrix SUM AB
 [[ 5 -3]
 [ 3  5]]
Matrix AB
 [[  4 -11]
 [ 12  -3]]
Matrix BA
 [[ 1 -8]
 [15  0]]


3. Из закономерностей сложения и умножения матриц на число можно
сделать вывод что матрицы одного размера образуют линейное ,
пространство Вычислите линейную комбинацию . 3 A −2B+4C для матриц

In [9]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Matrix A\n {A}')
print(f'Matrix B\n {B}')
print(f'Matrix C\n {C}')
print(f'Matrix 3A-2B+4C\n {3 * A + (-2) * B + 4* C}')

Matrix A
 [[ 1  7]
 [ 3 -6]]
Matrix B
 [[ 0  5]
 [ 2 -1]]
Matrix C
 [[ 2 -4]
 [ 1  1]]
Matrix 3A-2B+4C
 [[ 11  -5]
 [  9 -12]]


4. Дана матрица A=(
[4 1
5], [−2
2 3] )
. Вычислите A A
T
 и A
T
A.

In [11]:
A = np.array([[4, 1, 5], [-2, 2, 3]])
At = A.T
print(f'Matrix A\n {A}')
print(f'Matrix At\n {At}')
print(f'Matrix A*At\n {np.dot(A, At)}')
print(f'Matrix At*A\n {np.dot(At, A)}')

Matrix A
 [[ 4  1  5]
 [-2  2  3]]
Matrix At
 [[ 4 -2]
 [ 1  2]
 [ 5  3]]
Matrix A*At
 [[42  9]
 [ 9 17]]
Matrix At*A
 [[20  0 14]
 [ 0  5 11]
 [14 11 34]]


# Part 2

1.Вычислите определитель

In [17]:
import math as m
x = 1
s = m.sin(x)
c = m.cos(x)
A = np.array([[s, -c], [c, s]])
print(f'Matrix A\n {A}')
print(f'Matrix det(A)\n {np.linalg.det(A):.0f}')

Matrix A
 [[ 0.84147098 -0.54030231]
 [ 0.54030231  0.84147098]]
Matrix det(A)
 1


In [20]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Matrix A\n {A}')
print(f'Matrix det(A)\n {np.linalg.det(A):.0f}')

Matrix A
 [[4 2 3]
 [0 5 1]
 [0 0 9]]
Matrix det(A)
 180


In [21]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Matrix A\n {A}')
print(f'Matrix det(A)\n {np.linalg.det(A):.0f}')

Matrix A
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix det(A)
 0


2. Определитель матрицы A равен 4. : Найдите
а) d e t ( A^
2
);
б) d e t ( A^
T
);
в) d e t (2 A).

In [27]:
A = 4
print(f'det(A^2)\n {A * A}')
print(f'det(A^T)\n {A}')
# 𝑑𝑒𝑡𝐴^𝑇=𝑑𝑒𝑡𝐴
# det(2A)=2^n∗4=2^(n+2)

det(A^2)
 16
det(A^T)
 4


3.Доказать, что матрица вырожденная.

In [28]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Matrix A\n {A}')
print(f'Matrix det(A) {np.linalg.det(A):.0f}')
# Определитель равен 0 - матрица вырожденная.

Matrix A
 [[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Matrix det(A) 0


4.Найти ранг матрицы.

In [29]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Matrix A\n {A}')
print(f'Matrix rank(A)\n {np.linalg.matrix_rank(A)}')

Matrix A
 [[1 2 3]
 [1 1 1]
 [2 3 4]]
Matrix rank(A)
 2


In [30]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Matrix A\n {A}')
print(f'Matrix rank(A)\n {np.linalg.matrix_rank(A)}')

Matrix A
 [[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Matrix rank(A)
 3
